from __future__ import annotations

import json
import math
import struct
import wave
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path

from mido import Message, MetaMessage, MidiFile, MidiTrack

SAMPLE_RATE = 48_000
TICKS_PER_SECOND = 960


@dataclass(frozen=True)
class FixtureNote:
    pitch: int
    onset_seconds: float
    offset_seconds: float
    velocity: int = 90


@dataclass(frozen=True)
class Fixture:
    id: str
    category: str
    duration_seconds: float
    notes: list[FixtureNote]


FIXTURES = [
    Fixture(
        id="single_a4",
        category="synthetic_monophonic",
        duration_seconds=2.0,
        notes=[FixtureNote(69, 0.2, 1.8)],
    ),
    Fixture(
        id="three_note_phrase",
        category="synthetic_monophonic",
        duration_seconds=2.8,
        notes=[
            FixtureNote(60, 0.2, 0.8),
            FixtureNote(64, 1.0, 1.6),
            FixtureNote(67, 1.8, 2.4),
        ],
    ),
    Fixture(
        id="c_major_triad",
        category="synthetic_polyphonic",
        duration_seconds=2.0,
        notes=[
            FixtureNote(60, 0.2, 1.8, 82),
            FixtureNote(64, 0.2, 1.8, 82),
            FixtureNote(67, 0.2, 1.8, 82),
        ],
    ),
]


def create_smoke_dataset(output_directory: Path) -> Path:
    output_directory.mkdir(parents=True, exist_ok=True)
    samples: list[dict[str, str]] = []
    for fixture in FIXTURES:
        wav_path = output_directory / f"{fixture.id}.wav"
        midi_path = output_directory / f"{fixture.id}.mid"
        _write_wav(wav_path, fixture)
        _write_midi(midi_path, fixture.notes)
        samples.append(
            {
                "id": fixture.id,
                "category": fixture.category,
                "audio_path": wav_path.name,
                "reference_midi_path": midi_path.name,
                "audio_sha256": sha256(wav_path.read_bytes()).hexdigest(),
                "reference_midi_sha256": sha256(midi_path.read_bytes()).hexdigest(),
            }
        )
    manifest = {
        "schema_version": 1,
        "dataset": {
            "name": "Abachiwave synthetic audio-to-MIDI smoke",
            "version": "1",
            "license": "Generated by Abachiwave (MIT)",
            "license_url": "https://opensource.org/license/mit",
            "synthetic": True,
        },
        "onset_tolerance_seconds": 0.1,
        "offset_tolerance_seconds": 0.1,
        "offset_tolerance_ratio": 0.3,
        "samples": samples,
        "thresholds": {
            "overall": {
                "onset_pitch_f1_min": 0.4,
                "mean_onset_mae_ms_max": 100,
                "mean_duration_mae_ms_max": 150,
                "mean_velocity_mae_max": 30,
                "mean_onset_aligned_pitch_mae_semitones_max": 0.5,
                "empty_result_rate_max": 0,
                "median_real_time_factor_max": 10,
                "p95_latency_seconds_max": 30,
                "peak_memory_mib_max": 4096,
            },
            "synthetic_monophonic": {"onset_pitch_f1_min": 0.5},
            "synthetic_polyphonic": {"onset_pitch_f1_min": 0.1},
        },
    }
    manifest_path = output_directory / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return manifest_path


def _write_wav(path: Path, fixture: Fixture) -> None:
    frame_count = round(fixture.duration_seconds * SAMPLE_RATE)
    frames = bytearray()
    for frame_index in range(frame_count):
        timestamp = frame_index / SAMPLE_RATE
        amplitudes = [
            _note_sample(note, timestamp)
            for note in fixture.notes
            if note.onset_seconds <= timestamp < note.offset_seconds
        ]
        sample = sum(amplitudes) / max(1, len(amplitudes))
        frames.extend(struct.pack("<h", round(14_000 * sample)))
    with wave.open(str(path), "wb") as writer:
        writer.setnchannels(1)
        writer.setsampwidth(2)
        writer.setframerate(SAMPLE_RATE)
        writer.writeframes(frames)


def _note_sample(note: FixtureNote, timestamp: float) -> float:
    frequency = 440 * 2 ** ((note.pitch - 69) / 12)
    relative = timestamp - note.onset_seconds
    remaining = note.offset_seconds - timestamp
    fade = min(1.0, relative / 0.02, remaining / 0.02)
    return math.sin(2 * math.pi * frequency * relative) * max(0, fade)


def _write_midi(path: Path, notes: list[FixtureNote]) -> None:
    midi = MidiFile(type=1, ticks_per_beat=480)
    meta = MidiTrack()
    meta.append(MetaMessage("set_tempo", tempo=500_000, time=0))
    midi.tracks.append(meta)
    track = MidiTrack()
    events: list[tuple[int, int, FixtureNote]] = []
    for note in notes:
        events.append((round(note.onset_seconds * TICKS_PER_SECOND), 1, note))
        events.append((round(note.offset_seconds * TICKS_PER_SECOND), 0, note))
    previous_tick = 0
    for tick, event_kind, note in sorted(events, key=lambda event: (event[0], event[1])):
        delta = tick - previous_tick
        if event_kind == 1:
            track.append(Message("note_on", note=note.pitch, velocity=note.velocity, time=delta))
        else:
            track.append(Message("note_off", note=note.pitch, velocity=0, time=delta))
        previous_tick = tick
    midi.tracks.append(track)
    midi.save(path)
